apiVersion: apps/v1
kind: Deployment
metadata:
  # If we are deploying the main branch, we use the latest docker image. Otherwise we will use the
  # image with tag of release name
  name: app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # Deployment relates to pods that contain the label "project" with value "app"
  selector:
    matchLabels:
      project: app
  # Describe app pod
  template:
    metadata:
      labels:
        project: app
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
          env:
            - name: SERVICE
              value: app
            - name: PORT
              value: '3002'
            - name: API_BASE_URL
              value: api.{{ .Release.Namespace.svc.cluster.local }}
          ports:
            - containerPort: 3002
