apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    # Select pods that have label "project" with value app
    project: app
  ports:
    - name: app-listener
      protocol: TCP
      port: 3002 # outer port
      targetPort: 3002 # pod port
  type: ClusterIP
