apiVersion: apps/v1
kind: Deployment
metadata:
  # If we are deploying the main branch, we use the latest docker image. Otherwise we will use the
  # image with tag of release name
  name: cms
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # Deployment relates to pods that contain the label "project" with value "cms"
  selector:
    matchLabels:
      project: cms
  # Describe cms pod
  template:
    metadata:
      labels:
        project: cms
    spec:
      containers:
        - name: cms
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
          env:
            - name: SERVICE
              value: cms
            - name: PORT
              value: '3001'
          envFrom:
            - configMapRef:
                name: configmap
          ports:
            - containerPort: 3001
