name: Deploy github pages
description: Джоба отправляет все ранее созданные артефакты на github pages
inputs:
  token:
    description: Токен, позволяющий пушить в ветки $GITHUB_TOKEN
    type: string
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      uses: ./.github/workflows/prepare-environment
    - name: Save metadata about deployment
      uses: ./.github/workflows/deployment-metadata
      id: metadata
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        path: ./github-pages/${{ steps.metadata.outputs.branch }}
    - name: Upload new github-pages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages \
          --branch github-pages \
          --dest ./${{ steps.metadata.outputs.branch }}/${{ inputs.artifact-name }} \
          --dist ./github-pages/${{ steps.metadata.outputs.branch }} \
          --nojekyll \
          --remove ./${{ steps.metadata.outputs.branch }}/${{ inputs.artifact-name }} \
          --user "github-actions-bot <support+actions@github.com>"
