{{- $releaseNameWithРyphen:= printf "-%s" .Release.Name -}}
{{- $releaseNameWithTrailingDot:= printf "%s." .Release.Name -}}
{{- $postfix:= ternary "" $releaseNameWithРyphen (eq .Release.Name "colibrijs") -}}
{{- $appPostfix:= ternary "" $releaseNameWithTrailingDot (eq .Release.Name "colibrijs") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colibrijs-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - api{{ $postfix }}.colibrijs.io
      secretName: colibrijs
  rules:
    - host: api{{ $postfix }}.colibrijs.io
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: api
                port:
                  number: 3000

    - host: cms{{ $postfix }}.colibrijs.io
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: cms
                port:
                  number: 3001

    # For the main branch, here must be colibrijs.io
    # For other branches - releaseName.colibrijs.io
    - host: {{ $appPostfix }}colibrijs.io
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: app
                port:
                  number: 3002
