{{- $releaseNameWithРyphen:= printf "-%s" .Release.Name -}}
{{- $postfix:= ternary "" $releaseNameWithРyphen (eq .Release.Name "colibrijs") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colibrijs-ingress
spec:
  rules:
    - host: api{{ $postfix }}.colibrijs.io
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: api
                port:
                  number: 3000
