{{- $releaseImage:= printf "ivanpodgornov/colibrijs-api:%s" .Release.Name -}}
{{- $image:= ternary "ivanpodgornov/colibrijs-api:latest" $releaseImage (eq .Release.Name "colibrijs") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  # If we are deploying the main branch, we use the latest docker image. Otherwise we will use the
  # image with tag of release name
  name: api
spec:
  replicas: 1
  # Deployment relates to pods that contain the label "project" with value "api"
  selector:
    matchLabels:
      project: api
  # Describe api pod
  template:
    metadata:
      labels:
        project: api
    spec:
      containers:
        - name: api
          image: {{ $image }}
          env:
            - name: DATABASE_HOST
              value: database.{{ .Release.Namespace }}.svc.cluster.local
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_NAME
              value: colibrijs
            - name: DATABASE_PASSWORD
              value: {{ .Values.database.password }}
            - name: DATABASE_USER
              value: {{ .Values.database.user }}
          ports:
            - containerPort: 3000
