apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    # Select pods that have label "project" with value api
    project: api
  ports:
    - name: api-listener
      protocol: TCP
      port: 3000 # outer port
      targetPort: 3000 # pod port
  type: ClusterIP
