name: Setup kubernetes
inputs:
  cluster-url:
    description: Cluster' URL
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        mkdir -p ~/.local/bin
        chmod +x kubectl
        mv ./kubectl ~/.local/bin/kubectl
        kubectl version --client
    - name: Setup kubectl for working with remote cluster
      shell: bash
      run: |
        kubectl config set-cluster default --server=${{ inputs.cluster-url }} --insecure-skip-tls-verify
        kubectl config set-context default --cluster=default --namespace=default --user=cluster-admin
        kubectl config use-context default
        kubectl config view
    - name: Check nodes
      shell: bash
      run: kubectl get nodes
    - name: Install helm
      shell: bash
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version
