apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: database
    spec:
      containers:
        # The container name to execute pods
        - name: database
          # pull postgresimage from docker hub
          image: postgres:15-alpine
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: colibrijs
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
          # Mount real path only if main branch is deploying
          {{- if eq .Release.Name "colibrijs" }}
          volumeMounts:
            # The volume mounts for the container
            - mountPath: /var/lib/postgres/data
              name: db-data
          {{- end }}
      # Volumes attached to the pod
      {{- if eq .Release.Name "colibrijs" }}
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: db-persistent-volume-claim
      {{- end }}
