apiVersion: v1
kind: Service
metadata:
  # Name your service
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 5432
  # Pod to route service traffic
  selector:
    app: database
