name: Build all packages
on:
  workflow_call:
    outputs:
      example-artifact-name:
        description: Название артифакта с собранным example
        value: example
      storybook-artifact-name:
        description: Название артифакта с собранным storybook
        value: storybook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Build example
        run: npm run build --workspace @colibrijs/example
      - name: Build storybook
        run: npm run storybook:build --workspace @colibrijs/core
      - name: Save storybook build
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: ./packages/core/storybook-static
      - name: Save example build
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: ./packages/example/dist
