name: Build all packages
on:
  workflow_call:
    outputs:
      example-artifact-name:
        description: Название артифакта с собранным example
        value: example
      storybook-artifact-name:
        description: Название артифакта с собранным storybook
        value: storybook
      swagger-artifact-name:
        description: Название артифакта с собранным swagger
        value: swagger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Save metadata about deployment
        uses: ./.github/workflows/deployment-metadata
        id: metadata
      # -- Example --
      - name: Build example
        run: npm run build -w @colibrijs/example
      - name: Save example build
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: ./packages/example/dist
      # -- Storybook --
      - name: Build storybook
        run: |
          echo "$PULL_REQUEST_NUMBER"
          npm run storybook:build -w @colibrijs/core
        env:
          # Для ветки main - https://colibrijs.github.io/colibrijs/main/example/
          BRANCH_NAME: ${{ steps.metadata.outputs.branch }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event_name == 'pull_request' && github.event.number || '' }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          REFERENCE_STORYBOOK_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/main/storybook/
          TESTING_STORYBOOK_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.metadata.outputs.branch }}/storybook/
          EXAMPLE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.metadata.outputs.branch }}/example/
          COMMIT_SHA: ${{ github.sha }} # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: Save storybook build
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: |
            ./packages/core/storybook-static
            ./packages/core/screenshots
      # -- Swagger --
      - name: Build swagger
        run: npm run generate-swagger -w @colibrijs/api
      - name: Save swagger build
        uses: actions/upload-artifact@v4
        with:
          name: swagger
          path: |
            ./packages/api/redoc-static.html
            ./packages/api/openapi.json
