name: Deploy github pages

on:
  workflow_call:
    inputs:
      example-artifact-name:
        description: Имя артефакта из которого можно взять собранные компоненты example
        type: string
        required: true
      storybook-artifact-name:
        description: Имя артефакта из которого можно взять собранный сторибук
        type: string
        required: true
      swagger-artifact-name:
        description: Имя артефакта из которого можно взять собранный swagger
        type: string
        required: true
    outputs:
      example-url:
        description: Ссылка по которой доступны компоненты example
        value: ${{ jobs.deploy-example.outputs.url }}
      storybook-url:
        description: Ссылка по которой доступен сторибук
        value: ${{ jobs.deploy-storybook.outputs.url }}
      swagger-url:
        description: Ссылка по которой доступен swagger
        value: ${{ jobs.deploy-swagger.outputs.url }}

jobs:
  deploy-example:
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    environment:
      name: example-${{ github.head_ref }}
      url: ${{ steps.upload-example.outputs.url }}package.json
    outputs:
      url: ${{ steps.upload-example.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Put example to github pages
        id: upload-example
        uses: ./.github/workflows/put-artifact-to-github-pages
        with:
          artifact-name: ${{ inputs.example-artifact-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-storybook:
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    environment:
      name: storybook-${{ github.head_ref }}
      url: ${{ steps.upload-storybook.outputs.url }}
    outputs:
      url: ${{ steps.upload-storybook.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Put storybook to github pages
        id: upload-storybook
        uses: ./.github/workflows/put-artifact-to-github-pages
        with:
          artifact-name: ${{ inputs.storybook-artifact-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy-swagger:
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    environment:
      name: swagger-${{ github.head_ref }}
      url: ${{ steps.upload-swagger.outputs.url }}
    outputs:
      url: ${{ steps.upload-swagger.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Put swagger to github pages
        id: upload-swagger
        uses: ./.github/workflows/put-artifact-to-github-pages
        with:
          artifact-name: ${{ inputs.swagger-artifact-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
