name: Deploy github pages

on:
  workflow_call:
    inputs:
      playwright-report-artifact-name:
        description: Имя артефакта из которого можно взять playwright report
        type: string
        required: false
      storybook-artifact-name:
        description: Имя артефакта из которого можно взять собранный сторибук
        type: string
        required: true
      swagger-artifact-name:
        description: Имя артефакта из которого можно взять собранный swagger
        type: string
        required: true
    outputs:
      playwright-report-url:
        description: Ссылка по которой доступны компоненты example
        value: ${{ jobs.playwright-report.outputs.url }}
      storybook-url:
        description: Ссылка по которой доступен сторибук
        value: ${{ jobs.storybook.outputs.url }}
      swagger-url:
        description: Ссылка по которой доступен swagger
        value: ${{ jobs.swagger.outputs.url }}

jobs:
  deploy-github-pages:
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy artifacts to github pages
        uses: ./.github/workflows/deploy-artifacts-to-github-pages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  playwright-report:
    if: inputs.playwright-report-artifact-name
    needs: deploy-github-pages
    environment:
      name: playwright-report-${{ github.head_ref }}
      url: ${{ steps.resolve-playwright-report-url.outputs.url }}package.json
    outputs:
      url: ${{ steps.resolve-playwright-report-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve playwright report url
        id: resolve-playwright-report-url
        uses: ./.github/workflows/resolve-github-pages-url
        with:
          artifact-name: ${{ inputs.playwright-report-artifact-name }}

  storybook:
    needs: deploy-github-pages
    environment:
      name: storybook-${{ github.head_ref }}
      url: ${{ steps.resolve-storybook-url.outputs.url }}
    outputs:
      url: ${{ steps.resolve-storybook-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve storybook url
        id: resolve-storybook-url
        uses: ./.github/workflows/resolve-github-pages-url
        with:
          artifact-name: ${{ inputs.storybook-artifact-name }}

  swagger:
    needs: deploy-github-pages
    environment:
      name: swagger-${{ github.head_ref }}
      url: ${{ steps.resolve-swagger-url.outputs.url }}redoc-static.html
    outputs:
      url: ${{ steps.resolve-swagger-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve swagger url
        id: resolve-swagger-url
        uses: ./.github/workflows/resolve-github-pages-url
        with:
          artifact-name: ${{ inputs.swagger-artifact-name }}
