name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy-example:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: example-${{ github.head_ref }}
      url: ${{ steps.resolve-example-url.outputs.url }}
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    permissions:
      contents: write
    outputs:
      example-url: ${{ steps.resolve-example-url.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Deploy artifacts to github pages
        uses: ./.github/workflows/deploy-artifacts-to-github-pages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Resolve example url
        id: resolve-example-url
        uses: ./.github/workflows/resolve-github-pages-url
        with:
          artifact-name: ${{ needs.build.outputs.example-artifact-name }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      storybook-artifact-name: ${{ needs.build.outputs.storybook-artifact-name }}
      swagger-artifact-name: ${{ needs.build.outputs.swagger-artifact-name }}
