name: Main

on:
  push:
    branches:
      - main

jobs:
  storybook-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Build storybook
        run: npm run storybook:build --workspace @colibrijs/core
      - name: Save storybook build
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: ./packages/core/storybook-static

  storybook-deploy:
    needs: storybook-build
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      pull-requests: write
      id-token: write
