name: Pull request

on:
  pull_request:
    types:
      - closed

jobs:
  remove-github-pages:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      contents: write
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - name: Save metadata about deployment
        uses: ./.github/workflows/deployment-metadata
        id: metadata
      - name: Remove assets from github-pages relates to branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          git fetch origin github-pages
          git checkout github-pages
          git rm -rf ${{ steps.metadata.outputs.branch }}
          git commit -a -n -m "chore: remove ${{ steps.metadata.outputs.branch }}"
          git push origin github-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
