name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

jobs:
  build:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --ignore-scripts
          npx playwright install
      - name: Save metadata about deployment
        uses: ./.github/workflows/deployment-metadata
        id: metadata
      - name: Build cli
        run: |
          yarn workspace @colibrijs/cli build
          yarn install --frozen-lockfile
      - name: Build storybook for interaction tests
        run: yarn workspace @colibrijs/core build
        env:
          API_BASE_URL: ${{ github.event_name == 'pull_request' && format('http://api-{0}.{1}', steps.metadata.outputs.branch, vars.DOMAIN) || format('http://api.{1}', vars.DOMAIN) }}
          EXAMPLE_BUILD_SRC: http://localhost:3001/
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ steps.metadata.outputs.branch }}
      - name: Upload storybook for testing to artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-testing
          path: ./packages/core/storybook-static
      - name: Build storybook for github pages
        run: yarn workspace @colibrijs/core build
        env:
          API_BASE_URL: ${{ github.event_name == 'pull_request' && format('http://api-{0}.{1}', steps.metadata.outputs.branch, vars.DOMAIN) || format('http://api.{1}', vars.DOMAIN) }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ steps.metadata.outputs.branch }}
      - name: Upload github pages storybook to artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-github-pages
          path: ./packages/core/storybook-static
      - name: Build example
        run: yarn workspace @colibrijs/example build
      - name: Upload example build to artifact
        uses: actions/upload-artifact@v3
        with:
          name: example
          path: ./example/dist

  test:
    if: github.event.action != 'closed'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --ignore-scripts
          npx playwright install
      - name: Lint code
        run: yarn lint
      - if: github.event_name == 'pull_request'
        name: Validate commits in pull request
        run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run tests
        run: yarn test
      - name: Download example build
        uses: actions/download-artifact@v3
        with:
          name: example
          path: ./example/dist
      - name: Download storybook for interactions tests
        uses: actions/download-artifact@v3
        with:
          name: storybook-testing
          path: ./packages/core/storybook-static/
      - name: Test interactions
        run: yarn test:interactions

  deploy:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/deploy.yaml
    needs: test
    secrets: inherit
    permissions:
      packages: write

  remove-deploy:
    if: github.event.action == 'closed'
    secrets: inherit
    permissions:
      packages: write
    uses: ./.github/workflows/remove-deploy.yaml

  deploy-github-pages:
    if: github.event.action != 'closed'
    needs: test
    uses: ./.github/workflows/deploy-github-pages.yaml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  remove-github-pages:
    if: github.event.action == 'closed'
    uses: ./.github/workflows/remove-github-pages.yaml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

