on:
  pull_request:
    types:
      - review_requested

jobs:
  send-message-request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Send message to Telegram
        run: |
          npm exec control-freak request-review \
            -- --author ${{ github.actor }} \
            --reviewers "$(echo '${{ toJSON(github.event.pull_request.requested_reviewers) }}' | jq -r 'map(.login) | join(",")')" \
            --title "${{ github.event.pull_request.title }}" \
            --url ${{ github.event.pull_request.html_url }} \
            --telegram-bot-token ${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --telegram-chat-id ${{ secrets.TELEGRAM_CHAT_ID }}
