name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Lint
        run: npm run lint
      - name: Lint CSS
        run: npm run lint:css
      - name: Lint formatting
        run: npm run lint:formatting
      - name: Validate commits in pull request
        run: npx --no -- commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  deploy:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/deploy-github-pages.yml
    secrets: inherit
    with:
      example-artifact-name: ${{ needs.build.outputs.example-artifact-name }}
      storybook-artifact-name: ${{ needs.build.outputs.storybook-artifact-name }}

  test:
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Test unit
        run: npm run test:unit
      - name: Wait storybook
        run: |
          npm exec wait-storybook -- \
            --url ${{ needs.deploy.outputs.storybook-url }} \
            --commit-sha ${{ github.sha }} # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: Test interactions
        run: npm run test:interactions -w @colibrijs/core -- --url ${{ needs.deploy.outputs.storybook-url }}
      - name: Test e2e
        run: npm run test:e2e
        env:
          EXAMPLE_URL: ${{ needs.deploy.outputs.example-url }}
