on:
  pull_request:
    types:
      - review_requested

jobs:
  send-telegram-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/workflows/prepare-environment
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REQUESTED_REVIEWERS: ${{ toJson(github.event.pull_request.requested_reviewers) }}
        run: npx exec control-freak request-review -- --author ${{ github.actor }} --reviewer ivan-podgornov
