on:
  pull_request_review:
    types: [submitted]
jobs:
  send_telegram_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REVIEW_STATE: ${{ github.event.review.state }}
          REVIEW_BODY: ${{ github.event.review.body }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=Пользователь $GITHUB_ACTOR оставил что-то на Pull Request: \n *$PR_TITLE*. \n \n Статус ревью: *$REVIEW_STATE*. \n \n Комментарий: $REVIEW_BODY. \n \n [Ссылка]($PR_URL)" \
          -d "parse_mode=Markdown"
