name: Pull request review

on:
  pull_request_review:
    types: [submitted]

jobs:
  pull-request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Echo "Requesting review"
        run: echo "Ревью запрашиваю"
