on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  send-message-response-review:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm exec control-freak response-review \
          -- --author ${{ github.actor }} \
          --reviewers "$(echo '${{ toJSON(github.event.pull_request.requested_reviewers) }}' | jq -r 'map(.login) | join(",")')" \
          --title "${{ github.event.pull_request.title }}" \
          --url ${{ github.event.pull_request.html_url }} \
          --telegram-bot-token ${{ secrets.TELEGRAM_BOT_TOKEN }} \
          --telegram-chat-id ${{ secrets.TELEGRAM_CHAT_ID }}
