name: Pull request closed

on:
  pull_request:
    types:
      - closed

jobs:
  remove-github-pages:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - name: Save metadata about deployment
        uses: ./.github/workflows/deployment-metadata
        id: metadata
      - name: Remove assets relates to the pull request from github-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          git fetch origin github-pages
          git checkout github-pages
          git rm -rf ${{ steps.metadata.outputs.branch }}
          git commit -a -n -m "chore: remove ${{ steps.metadata.outputs.branch }}"
          git push origin github-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get GitHub App token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Remove storybook environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: storybook-${{ github.head_ref }}
      - name: Remove example environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: example-${{ github.head_ref }}
      - name: Remove swagger environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: swagger-${{ github.head_ref }}
      - name: Remove playwright report environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: playwright-report-${{ github.head_ref }}
