name: Remove example
on: workflow_call

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  ARTIFACT_NAME: github-pages

jobs:
  remove-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Save metadata about deployment
        uses: ./.github/workflows/deployment-metadata
        id: metadata
      - name: Download the github-pages artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: github-pages
          path: ./github-pages
      # actions/upload-pages-artifact puts all content from artifact into the tar archive. So,
      # before we will work with files, we need to extract them.
      - name: Extract github-pages archive
        if: steps.download-artifact.outcome == 'success'
        run: tar -xvf ./github-pages/artifact.tar
      - name: Remove old files for current branch and archive
        if: steps.download-artifact.outcome == 'success'
        run: |
          rm ./github-pages/artifact.tar
          rm -rf ./github-pages/${{ steps.metadata.outputs.branch }}/example
      - name: Upload new github-pages
        if: steps.download-artifact.outcome == 'success'
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: ./github-pages
          retention-days: 3
      - name: Deploy to GitHub Pages
        if: steps.download-artifact.outcome == 'success'
        id: deployment
        uses: actions/deploy-pages@v2
