on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        type: string
        required: true
      approved-screenshots:
        type: string
        required: true

jobs:
  screenshot-approve:
    runs-on: ubuntu-latest
    concurrency:
      group: screenshot-approve
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            <details>
              <summary>Подтверждаю изменения в скриншотах</summary>
              <pre id="screenshots-data">${{ inputs.approved-screenshots }}</div>
            </details>
          comment-tag: screenshot-approve
          mode: upsert
          pr-number: ${{ inputs.pull-request-number }}
